version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warped-aimagic-prod
    ports:
      - "3072:3072"
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - UPCITEMDB_API_KEY=${UPCITEMDB_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}